"""set nullable is true to school table

Revision ID: 4ed43df5952f
Revises: ef20c47db0ba
Create Date: 2022-08-31 17:02:45.107193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed43df5952f'
down_revision = 'ef20c47db0ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'instiName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'urlname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'paddress',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nostaff',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'noboys',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'coname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'medium',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'ofemail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'needs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'pincode',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofphno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'acadyear',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'cunofstu',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'comono',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nameofprince',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'yearofest',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'natureofaffili',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'cunofgirls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'nonteaching',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'coemailid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sclevel',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'headmono',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'heademailid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'headofphno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nameboard',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'instirecog',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'affiliationno',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'affiliyear',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'affilipertemp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'affilicondition',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'minstatus',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'christian',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'hindu',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'islam',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'others',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nonbelievers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'firecer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sanicer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'buildcer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'schown',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nametrust',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'registertrust',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'act',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'yearregis',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'registernu',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'validreg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'namepcm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'desigpcm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'addresspcm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'phonepcm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'emailpcm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tsc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tscmembers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tsctenure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'epcc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'epccmembers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'epcctenure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'pt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'ptmembers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'pttenure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sacouncil',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'samembers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'satenure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'ggcc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'schoolmc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'constitutionmc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'mcmembers',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'mctenure',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'schlocation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'scharea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'builduparea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'playarea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nobuildings',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'differentlyavail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'noofstairs',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nooflifts',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'croom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sroom',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'pl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'cl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'bl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'csl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'll',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'hsl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'library',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'audit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'cr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'up',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'prc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sickr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'canteen',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'orh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'sut',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'stut',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'speneeds',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'handlesn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'bw',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'bwyes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'cctv',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'ds',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'hmcamera',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'msg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'hmmalesg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'femalesg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'hwfemalesg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'drinkingwf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'pdf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'mms',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nobuses',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'gpsec',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nola',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'firstak',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'drinkingwa',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'nobusessc',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'efgfbp',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'freetsobts',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'lot',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'lct',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tnolb',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tnolm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tnold',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'tnoeb',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'oalr',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'slfps',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'provisionrt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('school', 'mmfas1',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('school', 'mmfas2',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('school', 'mmfas3',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('school', 'mmfas4',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('school', 'mmfas5',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('school', 'phmpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'phmpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'phmtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'phmtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'vppmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'vppfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'vptmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'vptfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PGTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PGTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PGTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PGTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'TGTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'TGTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'TGTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'TGTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PRTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PRTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PRTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PRTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'NTTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'NTTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'NTTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'NTTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'UTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'UTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'UTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'UTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Lpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Lpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Ltmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Ltfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Artspmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Artspfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Artstmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Artstfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Cpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Cpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Ctmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Ctfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'CLpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'CLpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'CLtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'CLtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'FMpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'FMpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'FMtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'FMtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Nursepmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Nursepfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Nursetmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'Nursetfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PTpmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PTpfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PTtmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'PTtfmale',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofmaper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofmatemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofmapart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofasper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofastemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'ofaspart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'clerkper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'clerktemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'clerkpart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'labper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'labtemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'labpart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'accountper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'accounttemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'accountpart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'peonsper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'peonstemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'peonspart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'othersper',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'otherstemp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'otherspart',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_activities',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_groups',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_community',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_school',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_zonal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_district',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_state',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_national',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_sports_international',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_school',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_zonal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_district',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_state',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_national',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_competition_international',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_school',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_zonal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_district',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_state',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_national',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('school', 'no_of_interprograms_international',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('school', 'no_of_interprograms_international',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_interprograms_national',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_interprograms_state',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_interprograms_district',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_interprograms_zonal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_interprograms_school',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_international',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_national',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_state',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_district',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_zonal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_competition_school',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_international',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_national',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_state',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_district',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_zonal',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_sports_school',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_community',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_groups',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'no_of_activities',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'otherspart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'otherstemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'othersper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'peonspart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'peonstemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'peonsper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'accountpart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'accounttemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'accountper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'labpart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'labtemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'labper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'clerkpart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'clerktemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'clerkper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofaspart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofastemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofasper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofmapart',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofmatemp',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'ofmaper',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Nursetfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Nursetmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Nursepfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Nursepmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'FMtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'FMtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'FMpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'FMpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'CLtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'CLtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'CLpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'CLpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Ctfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Ctmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Cpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Cpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Artstfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Artstmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Artspfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Artspmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Ltfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Ltmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Lpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'Lpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'UTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'UTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'UTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'UTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'NTTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'NTTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'NTTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'NTTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PRTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PRTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PRTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PRTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'TGTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'TGTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'TGTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'TGTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PGTtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PGTtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PGTpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'PGTpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'vptfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'vptmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'vppfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'vppmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'phmtfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'phmtmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'phmpfmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'phmpmale',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'mmfas5',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('school', 'mmfas4',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('school', 'mmfas3',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('school', 'mmfas2',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('school', 'mmfas1',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('school', 'provisionrt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'slfps',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'oalr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tnoeb',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tnold',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tnolm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tnolb',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'lct',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'lot',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'freetsobts',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'efgfbp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nobusessc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'drinkingwa',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'firstak',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nola',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'gpsec',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nobuses',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'mms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'pdf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'drinkingwf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'hwfemalesg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'femalesg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'hmmalesg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'msg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'hmcamera',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ds',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'cctv',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'bwyes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'bw',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'handlesn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'speneeds',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'rooms',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'stut',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sut',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'orh',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'canteen',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sickr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'prc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'up',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'cr',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'audit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'library',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'hsl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'll',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'csl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'bl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'cl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'pl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sroom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'croom',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nooflifts',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'noofstairs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'differentlyavail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nobuildings',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'playarea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'builduparea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'scharea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'schlocation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'mctenure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'mcmembers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'constitutionmc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'schoolmc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ggcc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'satenure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'samembers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sacouncil',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'pttenure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ptmembers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'pt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'epcctenure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'epccmembers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'epcc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tsctenure',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tscmembers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'tsc',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'emailpcm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'phonepcm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'addresspcm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'desigpcm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'namepcm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'validreg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'registernu',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'yearregis',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'act',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'registertrust',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nametrust',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'schown',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'buildcer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sanicer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'firecer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nonbelievers',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'others',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'islam',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'hindu',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'christian',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'minstatus',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'affilicondition',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'affilipertemp',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'affiliyear',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'affiliationno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'instirecog',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nameboard',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'headofphno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'heademailid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'headmono',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'sclevel',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'coemailid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'nonteaching',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'cunofgirls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'natureofaffili',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'yearofest',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'nameofprince',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'comono',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'cunofstu',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'acadyear',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ofphno',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'pincode',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'needs',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'ofemail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'medium',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'coname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'noboys',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'nostaff',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('school', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'paddress',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'urlname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('school', 'instiName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
