"""add additional columns to school table

Revision ID: 5d50e596296a
Revises: 102403a8c340
Create Date: 2022-08-31 09:50:24.994559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d50e596296a'
down_revision = '102403a8c340'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('no_of_activities', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_groups', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_community', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_school', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_zonal', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_district', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_state', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_national', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_sports_international', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_school', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_zonal', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_district', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_state', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_national', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_competition_international', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_school', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_zonal', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_district', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_state', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_national', sa.Integer(), nullable=False))
    op.add_column('school', sa.Column('no_of_interprograms_international', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'no_of_interprograms_international')
    op.drop_column('school', 'no_of_interprograms_national')
    op.drop_column('school', 'no_of_interprograms_state')
    op.drop_column('school', 'no_of_interprograms_district')
    op.drop_column('school', 'no_of_interprograms_zonal')
    op.drop_column('school', 'no_of_interprograms_school')
    op.drop_column('school', 'no_of_competition_international')
    op.drop_column('school', 'no_of_competition_national')
    op.drop_column('school', 'no_of_competition_state')
    op.drop_column('school', 'no_of_competition_district')
    op.drop_column('school', 'no_of_competition_zonal')
    op.drop_column('school', 'no_of_competition_school')
    op.drop_column('school', 'no_of_sports_international')
    op.drop_column('school', 'no_of_sports_national')
    op.drop_column('school', 'no_of_sports_state')
    op.drop_column('school', 'no_of_sports_district')
    op.drop_column('school', 'no_of_sports_zonal')
    op.drop_column('school', 'no_of_sports_school')
    op.drop_column('school', 'no_of_community')
    op.drop_column('school', 'no_of_groups')
    op.drop_column('school', 'no_of_activities')
    # ### end Alembic commands ###
