"""add a column pro

Revision ID: ab87399c0a7b
Revises: 869269e450c7
Create Date: 2022-09-01 09:10:03.263436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab87399c0a7b'
down_revision = '869269e450c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('login', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('product1', sa.Column('Namee', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product1', 'Namee')
    # op.drop_column('login', 'age')
    # ### end Alembic commands ###
