"""add 2pages column in school table

Revision ID: be6c5a725ba3
Revises: ab87399c0a7b
Create Date: 2022-09-01 15:08:17.133256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6c5a725ba3'
down_revision = 'ab87399c0a7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product1', 'Namee')
    op.drop_column('product1', 'namee')
    op.add_column('school', sa.Column('acad_year_begins', sa.String(), nullable=True))
    op.add_column('school', sa.Column('acad_year_ends', sa.String(), nullable=True))
    op.add_column('school', sa.Column('workingdays_21_22', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('workingdays_20_21', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('workingdays_19_20', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('eachday_workhours_21_22', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('eachday_workhours_20_21', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('eachday_workhours_19_20', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('totalhours_21_22', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('totalhours_20_21', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('totalhours_19_20', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('non_instruct_workdays_21_22', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('non_instruct_workdays_20_21', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('non_instruct_workdays_19_20', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('holiday_except_holidays_21_22', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('holiday_except_holidays_20_21', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('holiday_except_holidays_19_20', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('teaching_periods_perweek', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('faith_periods_perweek', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('period_duration', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('totalhours_forclubs', sa.Integer(), nullable=True))
    op.add_column('school', sa.Column('summer_timein', sa.String(), nullable=True))
    op.add_column('school', sa.Column('summer_timeout', sa.String(), nullable=True))
    op.add_column('school', sa.Column('winter_timein', sa.String(), nullable=True))
    op.add_column('school', sa.Column('winter_timeout', sa.String(), nullable=True))
    op.add_column('school', sa.Column('school_shift', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('school', 'school_shift')
    op.drop_column('school', 'winter_timeout')
    op.drop_column('school', 'winter_timein')
    op.drop_column('school', 'summer_timeout')
    op.drop_column('school', 'summer_timein')
    op.drop_column('school', 'totalhours_forclubs')
    op.drop_column('school', 'period_duration')
    op.drop_column('school', 'faith_periods_perweek')
    op.drop_column('school', 'teaching_periods_perweek')
    op.drop_column('school', 'holiday_except_holidays_19_20')
    op.drop_column('school', 'holiday_except_holidays_20_21')
    op.drop_column('school', 'holiday_except_holidays_21_22')
    op.drop_column('school', 'non_instruct_workdays_19_20')
    op.drop_column('school', 'non_instruct_workdays_20_21')
    op.drop_column('school', 'non_instruct_workdays_21_22')
    op.drop_column('school', 'totalhours_19_20')
    op.drop_column('school', 'totalhours_20_21')
    op.drop_column('school', 'totalhours_21_22')
    op.drop_column('school', 'eachday_workhours_19_20')
    op.drop_column('school', 'eachday_workhours_20_21')
    op.drop_column('school', 'eachday_workhours_21_22')
    op.drop_column('school', 'workingdays_19_20')
    op.drop_column('school', 'workingdays_20_21')
    op.drop_column('school', 'workingdays_21_22')
    op.drop_column('school', 'acad_year_ends')
    op.drop_column('school', 'acad_year_begins')
    op.add_column('product1', sa.Column('namee', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product1', sa.Column('Namee', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
