"""added fifth to eighth page school ui

Revision ID: de6382639aa6
Revises: cb0894660ffe
Create Date: 2022-09-26 12:35:50.482581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6382639aa6'
down_revision = 'cb0894660ffe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('schoolOwnedBy', sa.String(), nullable=True))
    op.add_column('school', sa.Column('nameOfTheTrustOrCompany', sa.String(), nullable=True))
    op.add_column('school', sa.Column('isTrustOrCompanyRegistered', sa.String(), nullable=True))
    op.add_column('school', sa.Column('underWhichAct', sa.String(), nullable=True))
    op.add_column('school', sa.Column('yearOfRegistration', sa.String(), nullable=True))
    op.add_column('school', sa.Column('registrationNo', sa.String(), nullable=True))
    op.add_column('school', sa.Column('validityOfRegistrationPeriod', sa.String(), nullable=True))
    op.add_column('school', sa.Column('nameOfPresidentOrChairman', sa.String(), nullable=True))
    op.add_column('school', sa.Column('designationOfPresidentOrChairman', sa.String(), nullable=True))
    op.add_column('school', sa.Column('addressOfPresidentOrChairman', sa.String(), nullable=True))
    op.add_column('school', sa.Column('phoneNoOfPresidentOrChairman', sa.String(), nullable=True))
    op.add_column('school', sa.Column('emailAddressOfPresidentOrChairman', sa.String(), nullable=True))
    op.add_column('school', sa.Column('governingBodyOfTrustOrCompany', sa.String(), nullable=True))
    op.add_column('school', sa.Column('NoOfMembersInTrustOrCompany', sa.String(), nullable=True))
    op.add_column('school', sa.Column('tenureOfEachMemberInTrust', sa.String(), nullable=True))
    op.add_column('school', sa.Column('educativePastoralCommunityCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('membersOfEducativePastoralComCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('tenureOfEducativePastoralComCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('parentTeacherAssosiateExecuteBody', sa.String(), nullable=True))
    op.add_column('school', sa.Column('membersOfParentTeacherExecuteBody', sa.String(), nullable=True))
    op.add_column('school', sa.Column('tenureOfParentTeacherExecuteBody', sa.String(), nullable=True))
    op.add_column('school', sa.Column('studentAssociationCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('membersOfStudentAssociationCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('tenureOfStudentAssociationCouncil', sa.String(), nullable=True))
    op.add_column('school', sa.Column('generalGrieveOrComplaintCell', sa.String(), nullable=True))
    op.add_column('school', sa.Column('schoolManagementCommittee', sa.String(), nullable=True))
    op.add_column('school', sa.Column('constitutionOfManagementCommittee', sa.String(), nullable=True))
    op.add_column('school', sa.Column('membersOfManagementCommittee', sa.String(), nullable=True))
    op.add_column('school', sa.Column('tenureOfManagementCommittee', sa.String(), nullable=True))
    op.add_column('school', sa.Column('isSchoolLocatedInRentedOrOwnBuilding', sa.String(), nullable=True))
    op.add_column('school', sa.Column('areaOfSchoolCampus', sa.String(), nullable=True))
    op.add_column('school', sa.Column('builtUpArea', sa.String(), nullable=True))
    op.add_column('school', sa.Column('playGroundArea', sa.String(), nullable=True))
    op.add_column('school', sa.Column('noOfBuildingsOrFloors', sa.String(), nullable=True))
    op.add_column('school', sa.Column('isProvisionsAvailableDifferently', sa.String(), nullable=True))
    op.add_column('school', sa.Column('noOfStairCase', sa.String(), nullable=True))
    op.add_column('school', sa.Column('noOfLifts', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'noOfLifts')
    op.drop_column('school', 'noOfStairCase')
    op.drop_column('school', 'isProvisionsAvailableDifferently')
    op.drop_column('school', 'noOfBuildingsOrFloors')
    op.drop_column('school', 'playGroundArea')
    op.drop_column('school', 'builtUpArea')
    op.drop_column('school', 'areaOfSchoolCampus')
    op.drop_column('school', 'isSchoolLocatedInRentedOrOwnBuilding')
    op.drop_column('school', 'tenureOfManagementCommittee')
    op.drop_column('school', 'membersOfManagementCommittee')
    op.drop_column('school', 'constitutionOfManagementCommittee')
    op.drop_column('school', 'schoolManagementCommittee')
    op.drop_column('school', 'generalGrieveOrComplaintCell')
    op.drop_column('school', 'tenureOfStudentAssociationCouncil')
    op.drop_column('school', 'membersOfStudentAssociationCouncil')
    op.drop_column('school', 'studentAssociationCouncil')
    op.drop_column('school', 'tenureOfParentTeacherExecuteBody')
    op.drop_column('school', 'membersOfParentTeacherExecuteBody')
    op.drop_column('school', 'parentTeacherAssosiateExecuteBody')
    op.drop_column('school', 'tenureOfEducativePastoralComCouncil')
    op.drop_column('school', 'membersOfEducativePastoralComCouncil')
    op.drop_column('school', 'educativePastoralCommunityCouncil')
    op.drop_column('school', 'tenureOfEachMemberInTrust')
    op.drop_column('school', 'NoOfMembersInTrustOrCompany')
    op.drop_column('school', 'governingBodyOfTrustOrCompany')
    op.drop_column('school', 'emailAddressOfPresidentOrChairman')
    op.drop_column('school', 'phoneNoOfPresidentOrChairman')
    op.drop_column('school', 'addressOfPresidentOrChairman')
    op.drop_column('school', 'designationOfPresidentOrChairman')
    op.drop_column('school', 'nameOfPresidentOrChairman')
    op.drop_column('school', 'validityOfRegistrationPeriod')
    op.drop_column('school', 'registrationNo')
    op.drop_column('school', 'yearOfRegistration')
    op.drop_column('school', 'underWhichAct')
    op.drop_column('school', 'isTrustOrCompanyRegistered')
    op.drop_column('school', 'nameOfTheTrustOrCompany')
    op.drop_column('school', 'schoolOwnedBy')
    # ### end Alembic commands ###
