"""set studentdata.id as string

Revision ID: edcf3659da80
Revises: 4ed43df5952f
Create Date: 2022-08-31 17:41:04.613027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcf3659da80'
down_revision = '4ed43df5952f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
