"""remove some columns from school table

Revision ID: ef20c47db0ba
Revises: 5d50e596296a
Create Date: 2022-08-31 10:53:35.799074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef20c47db0ba'
down_revision = '5d50e596296a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'labtotal')
    op.drop_column('school', 'FMTfmale')
    op.drop_column('school', 'LTfmale')
    op.drop_column('school', 'LTmale')
    op.drop_column('school', 'FMTmale')
    op.drop_column('school', 'UTTmale')
    op.drop_column('school', 'vpTfmale')
    op.drop_column('school', 'NurseTmale')
    op.drop_column('school', 'ArtsTfmale')
    op.drop_column('school', 'TotalTmale')
    op.drop_column('school', 'NTTTfmale')
    op.drop_column('school', 'PRTTmale')
    op.drop_column('school', 'NurseTfmale')
    op.drop_column('school', 'ofastotal')
    op.drop_column('school', 'clerktotal')
    op.drop_column('school', 'Totalpfmale')
    op.drop_column('school', 'vpTmale')
    op.drop_column('school', 'PGTTfmale')
    op.drop_column('school', 'ArtsTmale')
    op.drop_column('school', 'Totaltfmale')
    op.drop_column('school', 'UTTfmale')
    op.drop_column('school', 'PGTTmale')
    op.drop_column('school', 'accounttotal')
    op.drop_column('school', 'peonstotal')
    op.drop_column('school', 'CLTmale')
    op.drop_column('school', 'TotalTfmale')
    op.drop_column('school', 'Totaltmale')
    op.drop_column('school', 'ofmatotal')
    op.drop_column('school', 'Totalpmale')
    op.drop_column('school', 'CTfmale')
    op.drop_column('school', 'PTTfmale')
    op.drop_column('school', 'CTmale')
    op.drop_column('school', 'otherstotal')
    op.drop_column('school', 'NTTTmale')
    op.drop_column('school', 'PTTmale')
    op.drop_column('school', 'TGTTmale')
    op.drop_column('school', 'TGTTfmale')
    op.drop_column('school', 'CLTfmale')
    op.drop_column('school', 'phmTfmale')
    op.drop_column('school', 'PRTTfmale')
    op.drop_column('school', 'phmTmale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('phmTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PRTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('phmTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('CLTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('TGTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('TGTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('NTTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('otherstotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('CTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('CTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('Totalpmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('ofmatotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('Totaltmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('TotalTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('CLTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('peonstotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('accounttotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PGTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('UTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('Totaltfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('ArtsTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PGTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('vpTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('Totalpfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('clerktotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('ofastotal', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('NurseTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('PRTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('NTTTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('TotalTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('ArtsTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('NurseTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('vpTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('UTTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('FMTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('LTmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('LTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('FMTfmale', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('school', sa.Column('labtotal', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
