from sqlalchemy import Column,Integer,String,Boolean,ForeignKey,ARRAY
from .database import Base
from sqlalchemy.orm import relationship

class Product(Base):
    __tablename__="product1"
    id=Column(Integer,primary_key = True, nullable=False)
    name=Column(String,nullable=True)
    quantity=Column(Integer,nullable=True)

# class login(Base):

#     __tablename__="log"
#     username=Column(String,nullable=True,primary_key=True),
#     password=Column(String,nullable=True)



class School(Base):
    __tablename__="studentdata"
    id=Column(String,nullable=False,primary_key=True)
    username=Column(String,nullable=False)
    password=Column(String,nullable=False)
    name=Column(String,nullable=False)
    age=Column(Integer,nullable=False)
    gender=Column(String,nullable=False)
    fname=Column(String,nullable=False)
    mname=Column(String,nullable=False)
    phnumber=Column(Integer,nullable=False)
    address=Column(String,nullable=False)
#     # user=relationship("")




class Information(Base):
    __tablename__="school"
    id=Column(String,nullable=False,primary_key=True)
    instiName=Column(String,nullable=True)
    state=Column(String,nullable=True)
    urlname=Column(String,nullable=True)
    location=Column(String,nullable=True)
    paddress=Column(String,nullable=True)
    city=Column(String,nullable=True)
    nostaff=Column(Integer,nullable=True)
    noboys=Column(Integer,nullable=True)
    coname=Column(String,nullable=True)
    medium=Column(String,nullable=True)
    ofemail=Column(String,nullable=True)
    needs=Column(String,nullable=True)
    district=Column(String,nullable=True)
    pincode=Column(Integer,nullable=True)
    ofphno=Column(String,nullable=True)
    acadyear=Column(String,nullable=True)
    gender=Column(String,nullable=True)
    cunofstu=Column(Integer,nullable=True)
    comono=Column(String,nullable=True)
    nameofprince=Column(String,nullable=True)
    yearofest=Column(Integer,nullable=True)
    natureofaffili=Column(String,nullable=True)
    cunofgirls=Column(Integer,nullable=True)
    nonteaching=Column(Integer,nullable=True)
    coemailid=Column(String,nullable=True)
    sclevel=Column(String,nullable=True)
    headmono=Column(String,nullable=True)
    heademailid=Column(String,nullable=True)
    headofphno=Column(String,nullable=True)
    nameboard=Column(String,nullable=True)
    instirecog=Column(String,nullable=True)
    affiliationno=Column(String,nullable=True)
    affiliyear=Column(String,nullable=True)
    affilipertemp=Column(String,nullable=True)
    affilicondition=Column(String,nullable=True)
    minstatus=Column(String,nullable=True)
    christian=Column(String,nullable=True)
    hindu=Column(String,nullable=True)
    islam=Column(String,nullable=True)
    others=Column(String,nullable=True)
    nonbelievers=Column(String,nullable=True)
    firecer=Column(String,nullable=True)
    sanicer=Column(String,nullable=True)
    buildcer=Column(String,nullable=True)
    schown=Column(String,nullable=True)
    nametrust=Column(String,nullable=True)
    registertrust=Column(String,nullable=True)
    act=Column(String,nullable=True)
    yearregis=Column(String,nullable=True)
    registernu=Column(String,nullable=True)
    validreg=Column(String,nullable=True)
    namepcm=Column(String,nullable=True)
    desigpcm=Column(String,nullable=True)
    addresspcm=Column(String,nullable=True)
    phonepcm=Column(String,nullable=True)
    emailpcm=Column(String,nullable=True)
    tsc=Column(String,nullable=True)
    tscmembers=Column(String,nullable=True)
    tsctenure=Column(String,nullable=True)
    epcc=Column(String,nullable=True)
    epccmembers=Column(String,nullable=True)
    epcctenure=Column(String,nullable=True)
    pt=Column(String,nullable=True)
    ptmembers=Column(String,nullable=True)
    pttenure=Column(String,nullable=True)
    sacouncil=Column(String,nullable=True)
    samembers=Column(String,nullable=True)
    satenure=Column(String,nullable=True)
    ggcc=Column(String,nullable=True)
    schoolmc=Column(String,nullable=True)
    constitutionmc=Column(String,nullable=True)
    mcmembers=Column(String,nullable=True)
    mctenure=Column(String,nullable=True)
    schlocation=Column(String,nullable=True)
    scharea=Column(String,nullable=True)
    builduparea=Column(String,nullable=True)
    playarea=Column(String,nullable=True)
    nobuildings=Column(String,nullable=True)
    differentlyavail=Column(String,nullable=True)
    noofstairs=Column(String,nullable=True)
    nooflifts=Column(String,nullable=True)
    croom=Column(String,nullable=True)
    sroom=Column(String,nullable=True)
    pl=Column(String,nullable=True)
    cl=Column(String,nullable=True)
    bl=Column(String,nullable=True)
    ml=Column(String,nullable=True)
    csl=Column(String,nullable=True)
    ll=Column(String,nullable=True)
    hsl=Column(String,nullable=True)
    library=Column(String,nullable=True)
    audit=Column(String,nullable=True)
    cr=Column(String,nullable=True)
    up=Column(String,nullable=True)
    prc=Column(String,nullable=True)
    sickr=Column(String,nullable=True)
    canteen=Column(String,nullable=True)
    sr=Column(String,nullable=True)
    orh=Column(String,nullable=True)
    sut=Column(String,nullable=True)
    stut=Column(String,nullable=True)
    rooms=Column(String,nullable=True)
    speneeds=Column(String,nullable=True)
    handlesn=Column(String,nullable=True)
    bw=Column(String,nullable=True)
    bwyes=Column(String,nullable=True)
    cctv=Column(String,nullable=True)
    ds=Column(String,nullable=True)
    hmcamera=Column(String,nullable=True)
    msg=Column(String,nullable=True)
    hmmalesg=Column(String,nullable=True)
    femalesg=Column(String,nullable=True)
    hwfemalesg=Column(String,nullable=True)
    drinkingwf=Column(String,nullable=True)
    pdf=Column(String,nullable=True)
    mms=Column(String,nullable=True)
    nobuses=Column(String,nullable=True)
    gpsec=Column(String,nullable=True)
    nola=Column(String,nullable=True)
    firstak=Column(String,nullable=True)
    drinkingwa=Column(String,nullable=True)
    nobusessc=Column(String,nullable=True)
    efgfbp=Column(String,nullable=True)
    freetsobts=Column(String,nullable=True)
    # mmfainsch=Column(String,nullable=False)
    lot=Column(String,nullable=True)
    lct=Column(String,nullable=True)
    tnolb=Column(String,nullable=True)
    tnolm=Column(String,nullable=True)
    tnold=Column(String,nullable=True)
    tnoeb=Column(String,nullable=True)
    oalr=Column(String,nullable=True)
    slfps=Column(String,nullable=True)
    provisionrt=Column(String,nullable=True)
    mmfas1=Column(Boolean,nullable=True)
    mmfas2=Column(Boolean,nullable=True)
    mmfas3=Column(Boolean,nullable=True)
    mmfas4=Column(Boolean,nullable=True)
    mmfas5=Column(Boolean,nullable=True)
    phmpmale=Column(Integer,nullable=True)
    phmpfmale=Column(Integer,nullable=True)
    phmtmale=Column(Integer,nullable=True)
    phmtfmale=Column(Integer,nullable=True)
    # phmTmale=Column(Integer,nullable=False)
    # phmTfmale=Column(Integer,nullable=False)
    vppmale=Column(Integer,nullable=True)
    vppfmale=Column(Integer,nullable=True)
    vptmale=Column(Integer,nullable=True)
    vptfmale=Column(Integer,nullable=True)
    # vpTmale=Column(Integer,nullable=False)
    # vpTfmale=Column(Integer,nullable=False)
    PGTpmale=Column(Integer,nullable=True)
    PGTpfmale=Column(Integer,nullable=True)
    PGTtmale=Column(Integer,nullable=True)
    PGTtfmale=Column(Integer,nullable=True)
    # PGTTmale=Column(Integer,nullable=False)
    # PGTTfmale=Column(Integer,nullable=False)	
    TGTpmale=Column(Integer,nullable=True)
    TGTpfmale=Column(Integer,nullable=True)
    TGTtmale=Column(Integer,nullable=True)
    TGTtfmale=Column(Integer,nullable=True)
    # TGTTmale=Column(Integer,nullable=False)
    # TGTTfmale=Column(Integer,nullable=False)
    PRTpmale=Column(Integer,nullable=True)
    PRTpfmale=Column(Integer,nullable=True)
    PRTtmale=Column(Integer,nullable=True)
    PRTtfmale=Column(Integer,nullable=True)
    # PRTTmale=Column(Integer,nullable=False)
    # PRTTfmale=Column(Integer,nullable=False)
    NTTpmale=Column(Integer,nullable=True)
    NTTpfmale=Column(Integer,nullable=True)
    NTTtmale=Column(Integer,nullable=True)
    NTTtfmale=Column(Integer,nullable=True)
    # NTTTmale=Column(Integer,nullable=False)
    # NTTTfmale=Column(Integer,nullable=False)
    UTpmale=Column(Integer,nullable=True)
    UTpfmale=Column(Integer,nullable=True)
    UTtmale=Column(Integer,nullable=True)
    UTtfmale=Column(Integer,nullable=True)
    # UTTmale=Column(Integer,nullable=False)
    # UTTfmale=Column(Integer,nullable=False)
    Lpmale=Column(Integer,nullable=True)
    Lpfmale=Column(Integer,nullable=True)
    Ltmale=Column(Integer,nullable=True)
    Ltfmale=Column(Integer,nullable=True)
    # LTmale=Column(Integer,nullable=False)
    # LTfmale=Column(Integer,nullable=False)
    Artspmale=Column(Integer,nullable=True)
    Artspfmale=Column(Integer,nullable=True)
    Artstmale=Column(Integer,nullable=True)
    Artstfmale=Column(Integer,nullable=True)
    # ArtsTmale=Column(Integer,nullable=FTrue
    # ArtsTfmale=Column(Integer,nullable=False)
    Cpmale=Column(Integer,nullable=True)
    Cpfmale=Column(Integer,nullable=True)
    Ctmale=Column(Integer,nullable=True)
    Ctfmale=Column(Integer,nullable=True)
    # CTmale=Column(Integer,nullable=False)
    # CTfmale=Column(Integer,nullable=False)
    CLpmale=Column(Integer,nullable=True)
    CLpfmale=Column(Integer,nullable=True)
    CLtmale=Column(Integer,nullable=True)
    CLtfmale=Column(Integer,nullable=True)
    # CLTmale=Column(Integer,nullable=False)
    # CLTfmale=Column(Integer,nullable=False)
    FMpmale=Column(Integer,nullable=True)
    FMpfmale=Column(Integer,nullable=True)
    FMtmale=Column(Integer,nullable=True)
    FMtfmale=Column(Integer,nullable=True)
    # FMTmale=Column(Integer,nullable=False)
    # FMTfmale=Column(Integer,nullable=False)
    Nursepmale=Column(Integer,nullable=True)
    Nursepfmale=Column(Integer,nullable=True)
    Nursetmale=Column(Integer,nullable=True)
    Nursetfmale=Column(Integer,nullable=True)
    # NurseTmale=Column(Integer,nullable=False)
    # NurseTfmale=Column(Integer,nullable=False)
    PTpmale=Column(Integer,nullable=True)
    PTpfmale=Column(Integer,nullable=True)
    PTtmale=Column(Integer,nullable=True)
    PTtfmale=Column(Integer,nullable=True)
    # PTTmale=Column(Integer,nullable=False)
    # PTTfmale=Column(Integer,nullable=False)
    # Totalpmale=Column(Integer,nullable=False)
    # Totalpfmale=Column(Integer,nullable=False)
    # Totaltmale=Column(Integer,nullable=False)
    # Totaltfmale=Column(Integer,nullable=False)
    # TotalTmale=Column(Integer,nullable=False)
    # TotalTfmale=Column(Integer,nullable=False)
    ofmaper=Column(Integer,nullable=True)
    ofmatemp=Column(Integer,nullable=True)
    ofmapart=Column(Integer,nullable=True)
    # ofmatotal=Column(Integer,nullable=False)
    ofasper=Column(Integer,nullable=True)
    ofastemp=Column(Integer,nullable=True)
    ofaspart=Column(Integer,nullable=True)
    # ofastotal=Column(Integer,nullable=False)
    clerkper=Column(Integer,nullable=True)
    clerktemp=Column(Integer,nullable=True)
    clerkpart=Column(Integer,nullable=True)
    # clerktotal=Column(Integer,nullable=False)
    labper=Column(Integer,nullable=True)
    labtemp=Column(Integer,nullable=True)
    labpart=Column(Integer,nullable=True)
    # labtotal=Column(Integer,nullable=False)
    accountper=Column(Integer,nullable=True)
    accounttemp=Column(Integer,nullable=True)
    accountpart=Column(Integer,nullable=True)
    # accounttotal=Column(Integer,nullable=False)
    peonsper=Column(Integer,nullable=True)
    peonstemp=Column(Integer,nullable=True)
    peonspart=Column(Integer,nullable=True)
    # peonstotal=Column(Integer,nullable=False)
    othersper=Column(Integer,nullable=True)
    otherstemp=Column(Integer,nullable=True)
    otherspart=Column(Integer,nullable=True)
    # otherstotal=Column(Integer,nullable=False)

    no_of_activities=Column(Integer,nullable=True)
    no_of_groups=Column(Integer,nullable=True)
    no_of_community=Column(Integer,nullable=True)
    no_of_sports_school=Column(Integer,nullable=True)
    no_of_sports_zonal=Column(Integer,nullable=True)
    no_of_sports_district=Column(Integer,nullable=True)
    no_of_sports_state=Column(Integer,nullable=True)
    no_of_sports_national=Column(Integer,nullable=True)
    no_of_sports_international=Column(Integer,nullable=True)
    no_of_competition_school=Column(Integer,nullable=True)
    no_of_competition_zonal=Column(Integer,nullable=True)
    no_of_competition_district=Column(Integer,nullable=True)
    no_of_competition_state=Column(Integer,nullable=True)
    no_of_competition_national=Column(Integer,nullable=True)
    no_of_competition_international=Column(Integer,nullable=True)
    no_of_interprograms_school=Column(Integer,nullable=True)
    no_of_interprograms_zonal=Column(Integer,nullable=True)
    no_of_interprograms_district=Column(Integer,nullable=True)
    no_of_interprograms_state=Column(Integer,nullable=True)
    no_of_interprograms_national=Column(Integer,nullable=True)
    no_of_interprograms_international=Column(Integer,nullable=True)

    acad_year_begins=Column(String,nullable=True)
    acad_year_ends=Column(String,nullable=True)
    workingdays_21_22=Column(Integer,nullable=True)
    workingdays_20_21=Column(Integer,nullable=True)
    workingdays_19_20=Column(Integer,nullable=True)
    eachday_workhours_21_22=Column(Integer,nullable=True)
    eachday_workhours_20_21=Column(Integer,nullable=True)
    eachday_workhours_19_20=Column(Integer,nullable=True)
    totalhours_21_22=Column(Integer,nullable=True)
    totalhours_20_21=Column(Integer,nullable=True)
    totalhours_19_20=Column(Integer,nullable=True)
    non_instruct_workdays_21_22=Column(Integer,nullable=True)
    non_instruct_workdays_20_21=Column(Integer,nullable=True)
    non_instruct_workdays_19_20=Column(Integer,nullable=True)
    holiday_except_holidays_21_22=Column(Integer,nullable=True)
    holiday_except_holidays_20_21=Column(Integer,nullable=True)
    holiday_except_holidays_19_20=Column(Integer,nullable=True)
    teaching_periods_perweek=Column(Integer,nullable=True)
    faith_periods_perweek=Column(Integer,nullable=True)
    period_duration=Column(Integer,nullable=True)
    totalhours_forclubs=Column(Integer,nullable=True)
    summer_timein=Column(String,nullable=True)
    summer_timeout=Column(String,nullable=True)
    winter_timein=Column(String,nullable=True)
    winter_timeout=Column(String,nullable=True)
    school_shift=Column(String,nullable=True)
    scholarship= Column(ARRAY(String),nullable=True)







class Login(Base):
    __tablename__="login"
    id=Column(String,nullable=False,primary_key=True)
    name=Column(String,nullable=False)




class Log(Base):
    __tablename__="log"
    title=Column(String,nullable=False,primary_key=True)
    content=Column(String,nullable=False)


class Users(Base):
        __tablename__="users"
        id=Column(Integer,nullable=False,primary_key=True,autoincrement=True)
        username=Column(String,nullable=False)
        password=Column(String,nullable=False)
        name=Column(String,nullable=False)   
        gender=Column(Boolean,nullable=True,default=True)

class Posts(Base):
    __tablename__="posts"
    id=Column(Integer,nullable=False,primary_key=True,autoincrement=True)
    user_id=Column(Integer,ForeignKey("users.id",ondelete="CASCADE"),nullable=False)
    title=Column(String,nullable=False)
    content=Column(String,nullable=False)
    published=Column(Boolean,nullable=False,default=True)
    user=relationship("Users")



class Vote(Base):
    __tablename__="vote"
    posts_id=Column(Integer,ForeignKey("posts.id",ondelete='CASCADE'),primary_key=True)
    users_id=Column(Integer,ForeignKey("users.id",ondelete='CASCADE'),primary_key=True)




class Sample(Base):
    __tablename__="sample"
    username=Column(String,nullable=False,primary_key=True)
    password=Column(String,nullable=False)


